### ISSUE TITLE
Dumping XML and adapting Jetpack Compose

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/Paint#2]

**Comment by its-me-debk007** [comment]
I'm interested

**Comment by raghavtilak** [comment]
Hey @its-me-debk007 , Go for it 👍🏻 
Could you please brief us on your approach to this task?

**Comment by its-me-debk007** [comment]
- Created a Canvas, with drawing logic inside Modifier.pointerInput()
- Storing all strokes in a data structure
- Created a BrushStroke data class to store each stroke data

<img height="400" src="https://github.com/raghavtilak/Paint/assets/81604986/faae06ea-006e-41db-ac4a-44cc254070f2" />

<img height="250" src="https://github.com/raghavtilak/Paint/assets/81604986/756c275d-e473-4e08-a228-bfa5afdfa2b7" />

- Output

https://github.com/raghavtilak/Paint/assets/81604986/84a89213-9949-46fc-adf6-68855ebdd7a5

**Comment by raghavtilak** [comment]
Good start 👍🏻 
Are you thinking of smoothing the path? As I see in the Output, it's not quite smooth.
You can take some guidance from these videos. [link1](https://www.youtube.com/watch?v=vpDSvGhNy7o) [link2](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjHodXAy9uBAxV42DgGHcPKDVEQwqsBegQIJxAG&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DJujpmibSA2M&usg=AOvVaw0L0p0haNkTipnxQ6RKalVA&opi=89978449)
Hope they help you create a better solution!

**Comment by raghavtilak** [comment]
Hi @its-me-debk007 , 
Hope you are on it! Just wanted to know the progress on this issue. 
I was wondering if we could separate this issue into two separate tasks of converting the buttons to compose and later the canvas thing? What's your opinion?
Someone wants to contribute to the issue #4 .

**Comment by its-me-debk007** [comment]
Hi!
I'm close to implementing whole Jetpack Compose logic, including the functionalities of buttons

**Comment by raghavtilak** [comment]
Ok Great . Please carry on. 👍🏻

**Comment by its-me-debk007** [comment]
- I've implemented the features. There's just a small issue, that the image stored in the device doesn't show anything.
- Everything else is working completely fine

https://github.com/raghavtilak/Paint/assets/81604986/dd707606-00b9-4dc9-ac8b-8eb25cc3ce46

**Comment by its-me-debk007** [comment]
- Unfortunately, I'll be offline for today. So, I'll not be able to resolve this today. 
- If anyone else is interested, he/she can pick this issue, or I'll resolve it myself later.
- Should i raise a PR for this?

Here's the issue,

https://github.com/raghavtilak/Paint/assets/81604986/d54a60c9-9f72-49f8-8a0e-d4661f1ffed8

**Comment by raghavtilak** [comment]
Nice work @its-me-debk007 . Looks great 💯 
No issues take your time. Yes, please create a PR, so that others can look into this issue. We'll try to figure out something until you are unavailable.
You have done most of the part of the migration to Compose so I want you to finish this off too.
