### ISSUE TITLE
Adding Eraser functionality 

### ISSUE THREAD

**Issue by raghavtilak** [raghavtilak/Paint#4]
Currently, the app only supports undo, which completely removes the stroke.
An eraser functionality can be added which erases a particular path. Like you see in any Paint application.

**Comment by Yashraj254** [comment]
can i work on this issue?

**Comment by raghavtilak** [comment]
Hey @Yashraj254 ,
Yeah sure. But, I assigned issue #2 to @its-me-debk007 . He had already made some progress.
Once I get to know the current status of issue #2, I will make further decisions for this issue.
Are you comfortable with Jetpack Compose?

**Comment by Yashraj254** [comment]
@raghavtilak yeah sure, no issues, just one request , i tried finding an eraser icon similar to others but not sure which one to pick also having some dimension issues, do you have any **Eraser** svg icon that can be used for this functionality.

**Comment by raghavtilak** [comment]
Choose what you think is best, there's no issue with it.
By that time, you can do some r&d on how to implement this with both Compose and View/XML. You can also share your approach here.
Let me know if there's any other issue, am here to help✌🏻

**Comment by raghavtilak** [comment]
Hey @Yashraj254 ,
@its-me-debk007 is about to complete the Compose migration part. Once I merge it. You can then start with eraser functionality.
I hope you are ok with it.

**Comment by Yashraj254** [comment]
@raghavtilak yeah sure no problem, i have already implemented it, the Eraser simply uses the stroke that has a fixed color, i.e. the background color(color of canvas)

**Comment by raghavtilak** [comment]
Hey @Yashraj254 , I have merged the PR #11 . You can now start working on this issue. 😄
