### ISSUE TITLE
implement redo feature

### ISSUE THREAD

**Issue by its-me-debk007** [raghavtilak/Paint#9]
Can implement a Redo feature along with Undo for the user!

**Comment by its-me-debk007** [comment]
I wanna work on this issue

**Comment by raghavtilak** [comment]
Hey @its-me-debk007 
That would be great! Go for it 👍🏻 
Do commit the changes for #8 before working on it.

**Comment by its-me-debk007** [comment]
Please assign this issue to me

**Comment by its-me-debk007** [comment]
Please review the video

https://github.com/raghavtilak/Paint/assets/81604986/fa80407d-7725-4421-9915-74f28b38a5fb

**Comment by raghavtilak** [comment]
Looks perfect. Working as expected. 👍🏻

**Comment by its-me-debk007** [comment]
Please add hacktoberfest tag also
